//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""ActionMap"",
            ""id"": ""fbea48c2-ab7f-49ed-b93e-132815e95f26"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""1e6a9cb3-cda8-4bfd-9c23-8e5ab139dc60"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""2a46960a-b986-40f1-85d7-83bceebe0550"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShrinkFish"",
                    ""type"": ""Button"",
                    ""id"": ""eeef5b10-747f-40ee-8786-6732fcab0e9a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""43611bd8-802d-4d3b-a951-fa2dba6c7484"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1528adb4-ddc9-46ad-bd03-80c3cbb4d8cf"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2180c655-6798-44eb-9fca-a048f09656ba"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""63e50c38-813a-4f62-9105-530145f78843"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""07217727-a30c-4642-adc8-6f978704f70c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Controller"",
                    ""id"": ""2a728948-fc28-4be7-b2a6-7b06ff4a1717"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2c17b95c-2904-40f3-9e47-6e6f605452b9"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""84e48a6f-dd08-496a-b8e7-cf1397b90027"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""676cd817-ab26-4f2b-abbd-16fbfc2f8bd4"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""89722574-57fd-4c2b-a1ff-f532928ec069"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2d996b9e-b6f0-460f-ba52-ed698bc3d8e7"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b504535-8580-4c2c-8b87-6ba08b3f71bf"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""762beee7-7905-4330-8e61-6673a0339399"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShrinkFish"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4af8f749-584f-44ac-84ed-90ef6eabd7c1"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShrinkFish"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MenuMap"",
            ""id"": ""a6941131-7b75-4313-ab86-ec50ad2a77e3"",
            ""actions"": [
                {
                    ""name"": ""Nav"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5e08bde6-b2db-4754-91ba-316cd4b60990"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavUp"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0351bad2-347e-4191-b4b5-13f2e38c4494"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavDown"",
                    ""type"": ""PassThrough"",
                    ""id"": ""216c4ba3-24f4-48e8-b6d2-2458ff97eefa"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""f58c6e28-1086-4242-9ecb-4efbb8c1bc37"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""0a765cd1-a72b-45ce-ab61-38d351d284f4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NavMenu"",
                    ""type"": ""Button"",
                    ""id"": ""a1042370-8f8c-4a7f-b0a7-f52d819e976e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""517999b9-372c-4013-a53d-aa8d99ed6edd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nav"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d4bc37ec-ea0e-47a2-990c-9000f6c150e4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nav"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""37e8ada7-887f-4a78-82bd-982a84c3b506"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nav"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""61e2d6fd-7396-4808-9820-9cb19e361bc4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nav"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b6ac0e14-d6be-42c4-98e5-247a34c20e88"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nav"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""de065c43-4704-4a24-a760-10e5142926d8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavUp"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7287b72e-ef83-476b-afde-070098d191f0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""d3b9540c-090b-4c3b-aef7-a65b51cfc5e2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavDown"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""down"",
                    ""id"": ""647255c0-ba5a-4b89-aef9-903343bb3996"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Controller"",
                    ""id"": ""7340619a-de36-4a92-985b-faa043a9789f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nav"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""87016b05-e831-4a86-aad8-727193d0acc2"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nav"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4b4e9eda-606c-41b2-bf60-fcc94da16339"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nav"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f26b7ac1-79a8-40bf-ac1a-9093ee87f9d8"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nav"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4a5ec350-37e2-4224-a1aa-a1a05c6b48cc"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nav"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Controller"",
                    ""id"": ""b662e888-401b-4b57-9792-ffef0f6e9c0b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavUp"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""bf6e896c-5f62-4a65-90e6-9a944a814f12"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Controller"",
                    ""id"": ""b4d8315d-4061-49a8-a5f7-8646ca762917"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavDown"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cc1219e5-c41c-4f6e-bdd6-f4583283853c"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""622f7e75-dab1-49ff-bc56-63b28285f833"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be276663-c9da-4e36-9b83-5dff2fce0e11"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""643a2b35-29bc-406f-a52c-f9979097896c"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2cb7af34-5303-4601-be0c-efcc7342ae15"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""747b660e-2087-450a-917b-18f28f6fb6f9"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6553472a-8589-4ed1-ac9c-6d836bb5c4cc"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ActionMap
        m_ActionMap = asset.FindActionMap("ActionMap", throwIfNotFound: true);
        m_ActionMap_Movement = m_ActionMap.FindAction("Movement", throwIfNotFound: true);
        m_ActionMap_Dash = m_ActionMap.FindAction("Dash", throwIfNotFound: true);
        m_ActionMap_ShrinkFish = m_ActionMap.FindAction("ShrinkFish", throwIfNotFound: true);
        // MenuMap
        m_MenuMap = asset.FindActionMap("MenuMap", throwIfNotFound: true);
        m_MenuMap_Nav = m_MenuMap.FindAction("Nav", throwIfNotFound: true);
        m_MenuMap_NavUp = m_MenuMap.FindAction("NavUp", throwIfNotFound: true);
        m_MenuMap_NavDown = m_MenuMap.FindAction("NavDown", throwIfNotFound: true);
        m_MenuMap_Select = m_MenuMap.FindAction("Select", throwIfNotFound: true);
        m_MenuMap_Back = m_MenuMap.FindAction("Back", throwIfNotFound: true);
        m_MenuMap_NavMenu = m_MenuMap.FindAction("NavMenu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ActionMap
    private readonly InputActionMap m_ActionMap;
    private IActionMapActions m_ActionMapActionsCallbackInterface;
    private readonly InputAction m_ActionMap_Movement;
    private readonly InputAction m_ActionMap_Dash;
    private readonly InputAction m_ActionMap_ShrinkFish;
    public struct ActionMapActions
    {
        private @PlayerInputActions m_Wrapper;
        public ActionMapActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_ActionMap_Movement;
        public InputAction @Dash => m_Wrapper.m_ActionMap_Dash;
        public InputAction @ShrinkFish => m_Wrapper.m_ActionMap_ShrinkFish;
        public InputActionMap Get() { return m_Wrapper.m_ActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ActionMapActions set) { return set.Get(); }
        public void SetCallbacks(IActionMapActions instance)
        {
            if (m_Wrapper.m_ActionMapActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_ActionMapActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_ActionMapActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_ActionMapActionsCallbackInterface.OnMovement;
                @Dash.started -= m_Wrapper.m_ActionMapActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_ActionMapActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_ActionMapActionsCallbackInterface.OnDash;
                @ShrinkFish.started -= m_Wrapper.m_ActionMapActionsCallbackInterface.OnShrinkFish;
                @ShrinkFish.performed -= m_Wrapper.m_ActionMapActionsCallbackInterface.OnShrinkFish;
                @ShrinkFish.canceled -= m_Wrapper.m_ActionMapActionsCallbackInterface.OnShrinkFish;
            }
            m_Wrapper.m_ActionMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @ShrinkFish.started += instance.OnShrinkFish;
                @ShrinkFish.performed += instance.OnShrinkFish;
                @ShrinkFish.canceled += instance.OnShrinkFish;
            }
        }
    }
    public ActionMapActions @ActionMap => new ActionMapActions(this);

    // MenuMap
    private readonly InputActionMap m_MenuMap;
    private IMenuMapActions m_MenuMapActionsCallbackInterface;
    private readonly InputAction m_MenuMap_Nav;
    private readonly InputAction m_MenuMap_NavUp;
    private readonly InputAction m_MenuMap_NavDown;
    private readonly InputAction m_MenuMap_Select;
    private readonly InputAction m_MenuMap_Back;
    private readonly InputAction m_MenuMap_NavMenu;
    public struct MenuMapActions
    {
        private @PlayerInputActions m_Wrapper;
        public MenuMapActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Nav => m_Wrapper.m_MenuMap_Nav;
        public InputAction @NavUp => m_Wrapper.m_MenuMap_NavUp;
        public InputAction @NavDown => m_Wrapper.m_MenuMap_NavDown;
        public InputAction @Select => m_Wrapper.m_MenuMap_Select;
        public InputAction @Back => m_Wrapper.m_MenuMap_Back;
        public InputAction @NavMenu => m_Wrapper.m_MenuMap_NavMenu;
        public InputActionMap Get() { return m_Wrapper.m_MenuMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuMapActions set) { return set.Get(); }
        public void SetCallbacks(IMenuMapActions instance)
        {
            if (m_Wrapper.m_MenuMapActionsCallbackInterface != null)
            {
                @Nav.started -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnNav;
                @Nav.performed -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnNav;
                @Nav.canceled -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnNav;
                @NavUp.started -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnNavUp;
                @NavUp.performed -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnNavUp;
                @NavUp.canceled -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnNavUp;
                @NavDown.started -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnNavDown;
                @NavDown.performed -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnNavDown;
                @NavDown.canceled -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnNavDown;
                @Select.started -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnSelect;
                @Back.started -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnBack;
                @Back.performed -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnBack;
                @Back.canceled -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnBack;
                @NavMenu.started -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnNavMenu;
                @NavMenu.performed -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnNavMenu;
                @NavMenu.canceled -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnNavMenu;
            }
            m_Wrapper.m_MenuMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Nav.started += instance.OnNav;
                @Nav.performed += instance.OnNav;
                @Nav.canceled += instance.OnNav;
                @NavUp.started += instance.OnNavUp;
                @NavUp.performed += instance.OnNavUp;
                @NavUp.canceled += instance.OnNavUp;
                @NavDown.started += instance.OnNavDown;
                @NavDown.performed += instance.OnNavDown;
                @NavDown.canceled += instance.OnNavDown;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
                @NavMenu.started += instance.OnNavMenu;
                @NavMenu.performed += instance.OnNavMenu;
                @NavMenu.canceled += instance.OnNavMenu;
            }
        }
    }
    public MenuMapActions @MenuMap => new MenuMapActions(this);
    public interface IActionMapActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnShrinkFish(InputAction.CallbackContext context);
    }
    public interface IMenuMapActions
    {
        void OnNav(InputAction.CallbackContext context);
        void OnNavUp(InputAction.CallbackContext context);
        void OnNavDown(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
        void OnNavMenu(InputAction.CallbackContext context);
    }
}
